// <auto-generated />
using System;
using JobHunting.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobHunting.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917095136_UserAndUserProfile")]
    partial class UserAndUserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobHunting.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Industry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("IsMasterVersion")
                        .HasColumnType("bit");

                    b.Property<string>("ParsedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Type", "IsMasterVersion");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.Interview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Interview");
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppliedDate");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("NegotiationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("Offer");
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.StatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("StatusChange");
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tblUser", (string)null);
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tblProfile", (string)null);
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.Company", b =>
                {
                    b.OwnsOne("JobHunting.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LocationCity");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LocationCountry");

                            b1.Property<bool>("IsRemote")
                                .HasColumnType("bit")
                                .HasColumnName("IsRemote");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LocationState");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.Interview", b =>
                {
                    b.HasOne("JobHunting.Domain.Entities.JobApplication", null)
                        .WithMany("_interviews")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobHunting.Domain.ValueObjects.ContactInfo", "Interviewer", b1 =>
                        {
                            b1.Property<Guid>("InterviewId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("InterviewerEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("InterviewerName");

                            b1.Property<string>("Role")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("InterviewerRole");

                            b1.HasKey("InterviewId");

                            b1.ToTable("Interview");

                            b1.WithOwner()
                                .HasForeignKey("InterviewId");
                        });

                    b.Navigation("Interviewer");
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.JobApplication", b =>
                {
                    b.OwnsOne("JobHunting.Domain.ValueObjects.Money", "PostedSalaryRange", b1 =>
                        {
                            b1.Property<Guid>("JobApplicationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PostedSalaryMin");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PostedSalaryCurrency");

                            b1.HasKey("JobApplicationId");

                            b1.ToTable("JobApplications");

                            b1.WithOwner()
                                .HasForeignKey("JobApplicationId");
                        });

                    b.OwnsOne("JobHunting.Domain.ValueObjects.Money", "SalaryExpectation", b1 =>
                        {
                            b1.Property<Guid>("JobApplicationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SalaryExpectationAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SalaryExpectationCurrency");

                            b1.HasKey("JobApplicationId");

                            b1.ToTable("JobApplications");

                            b1.WithOwner()
                                .HasForeignKey("JobApplicationId");
                        });

                    b.OwnsOne("JobHunting.Domain.ValueObjects.ApplicationSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("JobApplicationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ReferralContactName")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SourceReferralName");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("SourceType");

                            b1.Property<string>("Url")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SourceUrl");

                            b1.HasKey("JobApplicationId");

                            b1.ToTable("JobApplications");

                            b1.WithOwner()
                                .HasForeignKey("JobApplicationId");
                        });

                    b.Navigation("PostedSalaryRange");

                    b.Navigation("SalaryExpectation");

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.Offer", b =>
                {
                    b.HasOne("JobHunting.Domain.Entities.JobApplication", null)
                        .WithOne("Offer")
                        .HasForeignKey("JobHunting.Domain.Entities.Offer", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobHunting.Domain.ValueObjects.Money", "AnnualBonus", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AnnualBonusAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AnnualBonusCurrency");

                            b1.HasKey("OfferId");

                            b1.ToTable("Offer");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.OwnsOne("JobHunting.Domain.ValueObjects.Money", "BaseSalary", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BaseSalaryAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BaseSalaryCurrency");

                            b1.HasKey("OfferId");

                            b1.ToTable("Offer");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.OwnsOne("JobHunting.Domain.ValueObjects.Money", "SigningBonus", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SigningBonusAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SigningBonusCurrency");

                            b1.HasKey("OfferId");

                            b1.ToTable("Offer");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.OwnsOne("JobHunting.Domain.ValueObjects.EquityGrant", "Equity", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CliffMonths")
                                .HasColumnType("int")
                                .HasColumnName("EquityCliffMonths");

                            b1.Property<decimal?>("Current409AValuation")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<int>("Shares")
                                .HasColumnType("int")
                                .HasColumnName("EquityShares");

                            b1.Property<decimal>("StrikePrice")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("EquityStrikePrice");

                            b1.Property<int>("VestingYears")
                                .HasColumnType("int")
                                .HasColumnName("EquityVestingYears");

                            b1.HasKey("OfferId");

                            b1.ToTable("Offer");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.Navigation("AnnualBonus");

                    b.Navigation("BaseSalary")
                        .IsRequired();

                    b.Navigation("Equity");

                    b.Navigation("SigningBonus");
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.StatusChange", b =>
                {
                    b.HasOne("JobHunting.Domain.Entities.JobApplication", null)
                        .WithMany("_history")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("JobHunting.Domain.Entities.User", null)
                        .WithOne("Profile")
                        .HasForeignKey("JobHunting.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.JobApplication", b =>
                {
                    b.Navigation("Offer");

                    b.Navigation("_history");

                    b.Navigation("_interviews");
                });

            modelBuilder.Entity("JobHunting.Domain.Entities.User", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
